### PR TITLE
Release for T3 contract update

### PR DESCRIPTION
**Pull request by mialbu**
The branch `release` is based on a commit that is aligned with the storage layout on the currently deployed bridge contract on T3. The new storage variables regarding `unclaimedRewards` and token bridges do not need initialization.

@txhsl Since these commits have been checked already and to not make you look through everything again, can you please just check these things:

- (**Critical:**) compare the storage layout between this and the deployed contract on T3 (see [here](https://github.com/bane-labs/bridge-evm-contracts/tree/1fc995f9c158a9948d5c2008db9773c9c81b2bfd/release/testnet/T3/v1/source))
- verify that the newly added vars don't need initialization

### CODE REVIEW

**Review by txhsl — APPROVED** [review]
If the field `gap` in `GasConfig` has never been initialized, then the storage change seems good.

**Comment by mialbu** [comment]
@txhsl 

The gap is never used, its values are the zero default value in the proxy. Also, now I've moved the code to the release directory and I've removed the constructor logic, since we don't need to have that in the logic contract.

Here just as an overview, here is the currently deployed storage layout:


```bash
| Name         | Type                                                 | Slot | Offset | Bytes | Contract                                               |
|--------------|------------------------------------------------------|------|--------|-------|--------------------------------------------------------|
| management   | contract IBridgeManagement                           | 0    | 0      | 20    | release/testnet/T3/v1/source/BridgeImpl.sol:BridgeImpl |
| locked       | bool                                                 | 0    | 20     | 1     | release/testnet/T3/v1/source/BridgeImpl.sol:BridgeImpl |
| gasBridge    | struct BridgeStorage.GasBridge                       | 1    | 0      | 320   | release/testnet/T3/v1/source/BridgeImpl.sol:BridgeImpl |
| claimableGas | mapping(uint64 => struct BridgeStorage.GasClaimable) | 11   | 0      | 32    | release/testnet/T3/v1/source/BridgeImpl.sol:BridgeImpl |
```

and here is the new one:

```bash
| Name             | Type                                                                  | Slot | Offset | Bytes | Contract                                                      |
|------------------|-----------------------------------------------------------------------|------|--------|-------|---------------------------------------------------------------|
| management       | contract IBridgeManagement                                            | 0    | 0      | 20    | release/testnet/T3/v2/source/bridge/BridgeImpl.sol:BridgeImpl |
| bridgePaused     | bool                                                                  | 0    | 20     | 1     | release/testnet/T3/v2/source/bridge/BridgeImpl.sol:BridgeImpl |
| gasBridge        | struct StorageTypes.GasBridge                                         | 1    | 0      | 320   | release/testnet/T3/v2/source/bridge/BridgeImpl.sol:BridgeImpl |
| claimableGas     | mapping(uint256 => struct StorageTypes.Claimable)                     | 11   | 0      | 32    | release/testnet/T3/v2/source/bridge/BridgeImpl.sol:BridgeImpl |
| unclaimedRewards | uint256                                                               | 12   | 0      | 32    | release/testnet/T3/v2/source/bridge/BridgeImpl.sol:BridgeImpl |
| tokenBridges     | mapping(address => struct StorageTypes.TokenBridge)                   | 13   | 0      | 32    | release/testnet/T3/v2/source/bridge/BridgeImpl.sol:BridgeImpl |
| tokenClaimables  | mapping(address => mapping(uint256 => struct StorageTypes.Claimable)) | 14   | 0      | 32    | release/testnet/T3/v2/source/bridge/BridgeImpl.sol:BridgeImpl |
| _status          | uint256                                                               | 15   | 0      | 32    | release/testnet/T3/v2/source/bridge/BridgeImpl.sol:BridgeImpl |
```

Note, that none of the newly added values need initialization.

**Comment by mialbu** [comment]
Here's the storage layout of the currently deployed management contract:

```bash
| Name               | Type      | Slot | Offset | Bytes | Contract                                                                   |
|--------------------|-----------|------|--------|-------|----------------------------------------------------------------------------|
| owner              | address   | 0    | 0      | 20    | release/testnet/T3/v1/source/BridgeManagementImpl.sol:BridgeManagementImpl |
| relayer            | address   | 1    | 0      | 20    | release/testnet/T3/v1/source/BridgeManagementImpl.sol:BridgeManagementImpl |
| validatorThreshold | uint8     | 1    | 20     | 1     | release/testnet/T3/v1/source/BridgeManagementImpl.sol:BridgeManagementImpl |
| validators         | address[] | 2    | 0      | 32    | release/testnet/T3/v1/source/BridgeManagementImpl.sol:BridgeManagementImpl |
| governor           | address   | 3    | 0      | 20    | release/testnet/T3/v1/source/BridgeManagementImpl.sol:BridgeManagementImpl |
| securityGuard      | address   | 4    | 0      | 20    | release/testnet/T3/v1/source/BridgeManagementImpl.sol:BridgeManagementImpl |
```

And here's the storage layout of the new management:

```bash
| Name               | Type      | Slot | Offset | Bytes | Contract                                                                              |
|--------------------|-----------|------|--------|-------|---------------------------------------------------------------------------------------|
| owner              | address   | 0    | 0      | 20    | release/testnet/T3/v2/source/management/BridgeManagementImpl.sol:BridgeManagementImpl |
| relayer            | address   | 1    | 0      | 20    | release/testnet/T3/v2/source/management/BridgeManagementImpl.sol:BridgeManagementImpl |
| validatorThreshold | uint8     | 1    | 20     | 1     | release/testnet/T3/v2/source/management/BridgeManagementImpl.sol:BridgeManagementImpl |
| validators         | address[] | 2    | 0      | 32    | release/testnet/T3/v2/source/management/BridgeManagementImpl.sol:BridgeManagementImpl |
| governor           | address   | 3    | 0      | 20    | release/testnet/T3/v2/source/management/BridgeManagementImpl.sol:BridgeManagementImpl |
| securityGuard      | address   | 4    | 0      | 20    | release/testnet/T3/v2/source/management/BridgeManagementImpl.sol:BridgeManagementImpl |
| funder             | address   | 5    | 0      | 20    | release/testnet/T3/v2/source/management/BridgeManagementImpl.sol:BridgeManagementImpl |
```

The only difference is the newly added funder in slot 5. While I didn't add an initializer in this contract, it's the default value address(0) until the owner uses `setFunder()`.

I've also removed the constructor logic here, since we don't need that in the logic contract.

**Comment by mialbu** [comment]
@txhsl and @chenquanyu
Please confirm that the removal of the `_checkProxy` and `_checkNotDelegated` as in commit 71dbaa4 are correct? This release is intended as a contract update and not a native contract from genesis.

**Comment by txhsl** [comment]
> @txhsl and @chenquanyu Please confirm that the removal of the `_checkProxy` and `_checkNotDelegated` as in commit [71dbaa4](https://github.com/bane-labs/bridge-evm-contracts/commit/71dbaa4bba049114ffd17b6266ea979fed524902) are correct? This release is intended as a contract update and not a native contract from genesis.

Yes, `_checkProxy` and `_checkNotDelegated` are override functions, so removing them just means using the original one. The reason we added these two in native contract is that `immutable` value can be only initialized in deploy codes instead of storage, but we only have runtime codes.

I think @chenquanyu has tested native contract upgrade, the removal looks fine.

**Pull request merged**
