### PR TITLE
add withdraw test cases

### PR DESCRIPTION
**Pull request by cloud8little**

### CODE REVIEW

**Comment by mialbu** [comment]
Hey @cloud8little,
are you using vscode for development? If so, could you add the following to your `settings.json`, so that we'll have the same lint settings:

```json
"editor.formatOnSave": true,
"[solidity]": {
	"editor.defaultFormatter": "NomicFoundation.hardhat-solidity"
}
```

**Comment by cloud8little** [comment]
> Hey @cloud8little, are you using vscode for development? If so, could you add the following to your `settings.json`, so that we'll have the same lint settings:
> 
> ```json
> "editor.formatOnSave": true,
> "[solidity]": {
> 	"editor.defaultFormatter": "NomicFoundation.hardhat-solidity"
> }
> ```

Yes, and the typescript is format with default vscode.

```
 "[typescript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    },
    "[solidity]": {
        "editor.defaultFormatter": "NomicFoundation.hardhat-solidity"
    }
```

**Comment by cloud8little** [comment]
seems the file is already formatted, no need to change.

**Comment by mialbu** [comment]
> seems the file is already formatted, no need to change.

Yes, it is here, you're right. I asked in the wrong pr, only in #14 the formatting was a bit off.

**Comment by cloud8little** [comment]
@mialbu  merge?

**Review by mialbu — APPROVED** [review]
:100:

**Pull request merged**
